### ISSUE TITLE
Speed up Dilithium with AVX2

### ISSUE THREAD

**Issue by bwesterb** [cloudflare/circl#113]
Our implementation of Dilithium (with AVX2) is faster than the C reference implementation, but it is still quite a bit slower than the optimised reference implementation.  There are still several functions that can be sped up easily with AVX2.

**Comment by armfazh** [comment]
I think this ticket can be closed now, is that right @bwesterb ?

**Comment by bwesterb** [comment]
There is still some room for optimisation, but the returns are getting smaller.

**Comment by armfazh** [comment]
Can we close this ticket for now, and open a new one in the future with new optimizations.

**Comment by bwesterb** [comment]
I made a second pass a month ago and couldn't find any low hanging fruit anymore.
