### ISSUE TITLE
Might be too early, but perhaps a tag release including Fp434?

### ISSUE THREAD

**Issue by kuking** [cloudflare/circl#116]
I hope you are doing well. I have been working on this: https://github.com/kuking/go-pqsw
I have been depending on tag v1.0.0 but Fp434 is only on master, so now I am on a master commit dep. It would be nice to use v1.0.1 or something like that... low prio, thank you for the library!

Thanks! Ed

**Comment by bwesterb** [comment]
@armfazh I also wouldn't mind a release after a public version `f1600x4` is in master.

**Comment by bwesterb** [comment]
^ which it is now.

**Comment by armfazh** [comment]
CIRCL has some new release tags while ago
