### ISSUE TITLE
ed25519 is not a drop-in replacement of crypto/ed25519

### ISSUE THREAD

**Issue by bwesterb** [cloudflare/circl#132]
- [ ] GetPublic -> Public
- [ ] NewKeyFromSeed returns *KeyPair instead of PrivateKey
- [ ] (check for others.)

**Comment by bwesterb** [comment]
@armfazh Fixing this would make it easier to copy code from Circl to our stdlib fork.

**Comment by claucece** [comment]
Sort of already discussed here: https://github.com/cloudflare/circl/issues/109, and there is already a PR for some of this: https://github.com/cloudflare/circl/pull/123

**Comment by bwesterb** [comment]
Would we want ed448 to be a drop-in replacement of ed25519 as well?

**Comment by chris-wood** [comment]
@bwesterb can we close this issue?

**Comment by bwesterb** [comment]
I just checked the API and it's a drop in replacement now!
