### ISSUE TITLE
Dilithium inconsistency

### ISSUE THREAD

**Issue by dhrubabasu** [cloudflare/circl#151]
Is this expected behavior?

```
dilithium.Mode4.PublicKeyFromBytes(b) // exists
mode4.PublicKeyFromBytes(b) // does not exist
```

This seems to be caused by the method existing [here](https://github.com/cloudflare/circl/blob/master/sign/dilithium/mode4.go#L51) but not [here](https://github.com/cloudflare/circl/blob/master/sign/dilithium/mode4/dilithium.go).

**Comment by bwesterb** [comment]
This is intended.  There are two APIs to access Dilithium:

1. The dynamic API accessible from the top-level package.
2. The static API accessible from the sub packages for each mode.

If you know which mode you want to use compile time and want to avoid allocations, the second API is better.  The first API is a bit simpler and allows to chose which mode you want to use at runtime.

(B.t.w. to deserialise a public key in the second API, you simply use the BinaryUnmarshaler interface on the PublicKey type.)
