### ISSUE TITLE
Implement OPRF

### ISSUE THREAD

**Issue by claucece** [cloudflare/circl#153]
- [x] Approve the API
- [x] Review @armfazh decaf's implementation, and see if it will easily fit into this.
- [x] Import the code from the voprf repo; but change it to the current API and draft. Potentially only make it work with P-256.
- [x] Check against the sage repo and the test vectors

**Comment by claucece** [comment]
Some missing parts:

- [ ] Add VerifyFinalize
- [ ] FullEvaluate

**Comment by chris-wood** [comment]
#154 landed, so this is done! Closing.
