### ISSUE TITLE
Switch to internal sha3

### ISSUE THREAD

**Issue by bwesterb** [cloudflare/circl#157]
Currently we have a copy of x/crypto/sha3 in circl that only contains shake.  For Kyber we use x/crypto/sha3 for SHA3.  We should update our copy of x/crypto/sha3 to accommodate SHA3.

**Comment by armfazh** [comment]
Could you please remind me what features added in the internal package?
I was thinking that we could move the package from internal to public. 
Also, the stdlib sha3 also includes cshake, do we want to include it too?

**Comment by bwesterb** [comment]
> Could you please remind me what features added in the internal package?

1. We expose

    1. RC
    2. F1600

    These are used in the f1600x4.
2. We prevent allocation by exposing the `State` struct.


> I was thinking that we could move the package from internal to public.

Then we have to maintain API stability, which I think would be messy.

> Also, the stdlib sha3 also includes cshake, do we want to include it too?

I removed it because preventing allocations there turned out to be a bit tricky.  We can add it back, of course.

**Comment by claucece** [comment]
I like this idea a lot.

**Comment by armfazh** [comment]
Thanks, let's mantain the package as internal.
