### ISSUE TITLE
Large documentation

### ISSUE THREAD

**Issue by bwesterb** [cloudflare/circl#167]
I'd like to include some rather large images such as [this one](http://westerbaan.name/~bas/images/kybavx2.svg.gz).

It would bloat the circl repository to include it directly.  Perhaps a separate circl-docs repo?  @armfazh

**Comment by armfazh** [comment]
You can include further documentation in the [wiki space](https://github.com/cloudflare/circl/wiki).
For that specific image, you can produce a smaller png, and add a link you the svg file.

**Comment by bwesterb** [comment]
Ah, yes, of course. Done.
