### ISSUE TITLE
Generic SIDH implementation using AMD64

### ISSUE THREAD

**Issue by haggj** [cloudflare/circl#187]
On my local AMD64 machine I can not run generic SIDH test or benchmarks:

**$ NOASM=1 make test**

```
rm -rf [...]/circl/build
go vet ./...
go test  --tags noasm -v               ./...
?       github.com/cloudflare/circl     [no test files]
?       github.com/cloudflare/circl/dh  [no test files]
# github.com/cloudflare/circl/dh/sidh/internal/p434
dh/sidh/internal/p434/fp2.go:14:2: undefined: mulP434
dh/sidh/internal/p434/fp2.go:15:2: undefined: rdcP434
dh/sidh/internal/p434/fp2.go:58:2: undefined: addP434
dh/sidh/internal/p434/fp2.go:59:2: undefined: addP434
dh/sidh/internal/p434/fp2.go:63:2: undefined: subP434
dh/sidh/internal/p434/fp2.go:64:2: undefined: subP434
dh/sidh/internal/p434/fp2.go:82:2: undefined: mulP434
dh/sidh/internal/p434/fp2.go:83:2: undefined: mulP434
dh/sidh/internal/p434/fp2.go:84:2: undefined: subP434
dh/sidh/internal/p434/fp2.go:85:2: undefined: subP434
dh/sidh/internal/p434/fp2.go:85:2: too many errors
```

Looking into _circl/dh/sidh/internal/p434/mulP434/arith_generic.go_ I noticed the following line of code:
`// +build noasm,arm64 !amd64`
At the same time the appropriate files for the other parameters (p503, p751) implement the following tag logic:
`// +build noasm !amd64,!arm64`
Changing the line for p434 accordingly seems to fix the tests for SIDH.

**Comment by armfazh** [comment]
@haggj thanks for reporting this issue, we have updated the build tags. let us know if it works now.
