### ISSUE TITLE
Kyber (NIST round 3) incompatibility with liboqs Kyber

### ISSUE THREAD

**Issue by david415** [cloudflare/circl#213]
See: https://github.com/open-quantum-safe/liboqs/issues/909

Although not automated, confirming this incompatibility is simple. First I used Circl's golang kyber in a test to generate a Kyber1024 key pair and printed them as hex:
 
https://github.com/david415/cryptocomrade/blob/master/go/kyber/kyber_test.go#L34

Next I used the previously mentioned public key in a test which uses the oqs rust crate to "encapsulate" a shared secret. I print the hex of the shared secret as well as it's ciphertext:

https://github.com/david415/cryptocomrade/blob/master/rust/src/kyber.rs#L21

After that I modified the previously mentioned golang test to "decapsulate" the ciphertext:

https://github.com/david415/cryptocomrade/blob/master/go/kyber/kyber_test.go#L60

This shows that the two implementations generate different "shared secrets".

Please do let me know if there is anything else I can do to help. I sincerely wish this incompatibility to be fixed because I am using both the oqs rust crate and the circl go library in my software which will hopefully one day enable people to communicate more freely.

**Comment by thomwiggers** [comment]
The oqs crate that's currently on crates.io uses Kyber Round 2. Unfortunately the Rust crate is waiting for liboqs to do a release before I want to bump the version.

**Comment by david415** [comment]
Sorry for my confusion!
