### ISSUE TITLE
hpke: Export common errors

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/circl#271]
There was an interesting edge case in Cloucflare-Go's ECH implementation where failure to parse an HPKE public key triggered a server abort instead of falling back to the outer handshake as it should. The solution (https://github.com/cloudflare/go/pull/95) was to check for a particular HPKE error: https://github.com/cloudflare/circl/blob/master/hpke/hpke.go#L290.

Because the error isn't exported, the only way to check for it is to compare `err.Error()` to `"hpke: invalid KEM public key"`. This check will be invalid if the output of `err.Error()` ever changes. To solve this problem, I would like to propose we export common errors from HPKE.

**Comment by armfazh** [comment]
@cjpatton, does #276  fixed this issue?

**Comment by cjpatton** [comment]
Yes, thanks very much.
