### ISSUE TITLE
TestScalarMult/wrong_P is failing with Go 1.18

### ISSUE THREAD

**Issue by GlenPickle** [cloudflare/circl#329]
Per https://go.dev/doc/go1.18: "Operating on invalid curve points (those for which the IsOnCurve method returns false, and which are never returned by [Unmarshal](https://go.dev/pkg/crypto/elliptic#Unmarshal) or a Curve method operating on a valid point) has always been undefined behavior, can lead to key recovery attacks, and is now unsupported by the new backend."

This change means that TestScalarMult/wrong_P will always fail, and should be removed.

**Comment by armfazh** [comment]
Have you take a look at #327 
I rewrote that test to one that is equivalent.
