### ISSUE TITLE
Remove sike implementations as those are not considered secure anymore 

### ISSUE THREAD

**Issue by EKTehtris** [cloudflare/circl#358]
According to this : https://ellipticnews.wordpress.com/2022/07/31/breaking-supersingular-isogeny-diffie-hellman-sidh/ ,SIDH and SIKE are no longer considered secure

**Comment by EKTehtris** [comment]
For more note, please consult this paper : https://eprint.iacr.org/2022/975

**Comment by bwesterb** [comment]
See #359

**Comment by EKTehtris** [comment]
Thx !
