### ISSUE TITLE
R=2^32 ?

### ISSUE THREAD

**Issue by kriskwiatkowski** [cloudflare/circl#365]
Shouldn't this be?
(256)⁻¹ R² mod q, where R = 2³²

```
> sage -c "Q=8380417;L=32;R=2^L;print((R^2)/(2^8)%Q)"
41978
```

https://github.com/cloudflare/circl/blob/0a9554f37a47ea95082a1c70c0551377007c5ac9/sign/dilithium/internal/common/params/params.go#L12

**Comment by bwesterb** [comment]
Yeah, that's a typo.

**Comment by kriskwiatkowski** [comment]
Thank you. I started to think, I'm missing something here.
