### ISSUE TITLE
"code.cfops.it/crypto/cpabe" import not in go.mod

### ISSUE THREAD

**Issue by sashamor** [cloudflare/circl#385]
There's an import of "code.cfops.it/crypto/cpabe" in the testdata folder:

https://github.com/cloudflare/circl/blob/main/abe/cpabe/tkn20/testdata/serialize.go#L7

This is breaking Bazel imports of [pkgsite](https://pkg.go.dev/golang.org/x/pkgsite), which indirectly depends on this library:

> compilepkg: missing strict dependencies:
        /home/.../sandbox/linux-sandbox/1763/execroot/__main__/external/com_github_cloudflare_circl/abe/cpabe/tkn20/testdata/serialize.go: import of "code.cfops.it/crypto/cpabe"

Any chance of getting this added to the `go.mod` file, so [Gazelle](https://github.com/bazelbuild/rules_go) can generate BUILD files for it correctly?

**Comment by bwesterb** [comment]
Should be fixed in v1.3.1 that was just released.

**Comment by sashamor** [comment]
Thank for the prompt reply & fix! 🎉
