### ISSUE TITLE
KEM schemes need NewEmptyPublicKey and NewEmptyPrivateKey methods

### ISSUE THREAD

**Issue by david415** [cloudflare/circl#389]
Dear circl devs,

I need a way to create empty public kyber kem keys so that I can initialize my data structures which encapsulate these keys and then unmarshal them from a binary blob. I feel like this is a fairly normal thing to do with cryptographic key material. Have I missed another obvious solution to this problem?

**Comment by bwesterb** [comment]
For those who wonder the same and don't figure it out themselves: an empty public key doesn't need to be initialized. Instead, to unmarshal a public key, simply call `UnmarshalBinaryPublicKey()` on the `scheme`, which returns the `PublicKey` object.
