### ISSUE TITLE
go plugin not compiling

### ISSUE THREAD

**Issue by JensAc** [cloudflare/circl#391]
Hi, 
when I try to build a plugin containing circl like so
```
go build -buildmode=plugin
```
I get:
```
asm: fp_amd64.s:68: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00215 (....l/vendor/github.com/cloudflare/circl/math/fp25519/fp_amd64.s:68)  MULXQ   24(SI), AX, R15
asm: assembly failed
```

I am sorry, but I have no idea on debugging this. I found similar [issues](https://github.com/klauspost/compress/issues/428) which let me assume that some upstream change could be required. If you find time to look into this, I would really appreciate your help.

**Comment by JensAc** [comment]
So, now I did some research on this. This issue is that the R15 register cannot be used in assembly, when compiling in plugin mode. Therefore, replacing the R15 register by the DI register could do the trick, as also done [here](https://github.com/cespare/xxhash/commit/e7a6b52374f7e2abfb8abb27249d53a1997b09a7). Would that be an option for this codebase as well? If yes, I could file a PR.

**Comment by bwesterb** [comment]
Sorry for the late reply. I think your analysis is correct and I think we would take that PR. @armfazh you agree?

**Comment by armfazh** [comment]
Update, I have checked spots in which compilation does not succeed due to R15 register.
I am working on patching the code, and pretty close to have CIRCL compiling as a plugin.
