### ISSUE TITLE
OPRF - Export Public Key

### ISSUE THREAD

**Issue by krissully** [cloudflare/circl#401]
Is there a way to use a private key in pem format when configuring an oprf server?

**Comment by bwesterb** [comment]
@cjpatton

**Comment by armfazh** [comment]
The format of a OPRF keys are raw scalar and curve point.
https://github.com/cloudflare/circl/blob/main/oprf/keys.go#L21

For example, for P256, the private key is a 32-byte number and the public key is a compressed point in 33 bytes.

Assuming your `key.pem` was generated as: 
```sh
$ openssl ecparam -name prime256v1 -genkey -out key.pem 
```
You can recover the internal values with:
```sh
$ openssl ec -in key.pem  -text -noout
```

In Go, you can do so similarly as in [ParseECPrivateKey](https://cs.opensource.google/go/go/+/refs/tags/go1.20:src/crypto/x509/sec1.go;l=84), but instead use the UnmarshalBinary method from the OPRF package.

**Comment by armfazh** [comment]
Closing as answered.
