### ISSUE TITLE
[QUESTION]: is blindsign package post-quantum secure ?

### ISSUE THREAD

**Issue by devthejo** [cloudflare/circl#441]
Hello,

Question: is the blindsign package post-quantum secure or, as it's based on RSA, it suffer from same vuln and not secure at post-quantum area ?

Thanks

**Comment by devthejo** [comment]
OK, got it, thanks for your reactivity.

Without wanting to abuse your time, I've two more question:
- is this planned on the circl roadmap to develop a post-quantum secure blind-signing package (and as the one based on RSA with deterministic signature feature) ?
- If not, from your perspective, what would be the good way to start working on this, what would be the lib you would choose to work on top (if anyone viewing this message has an idea or suggestion, I post this question as a bottle in the sea) ?

**Comment by bwesterb** [comment]
Post-quantum blind signatures are still very much an active research area. We're interested in them for post-quantum privacy pass/blind tokens. That led us to [this work presented at RWC this year](https://youtu.be/IAOWRO9Qn10?t=3103). I expect much better schemes to be announced the coming years. There are no practical off the shelf implementations though.

**Comment by armfazh** [comment]
Derived from ia.cr/2023/414, there is this implementation that you may find useful.
https://github.com/guruvamsi-policharla/zkdilithium
