### ISSUE TITLE
Unusual Behavior: Successful Signature Verification After Altering Private Key

### ISSUE THREAD

**Issue by ChristianOConnor** [cloudflare/circl#463]
I am using the Dilithium5 mode provided by the github.com/cloudflare/circl/sign/dilithium package. I've noticed an unusual behavior where, after manually altering a section of the private key, signatures generated with the modified key are still successfully verified using the original public key.

Steps to reproduce:

    Generate a Dilithium5 key pair using the GenerateKey(nil) function.
    Save the original private key and public key (in hexadecimal).
    Manually alter a section of the private key. For instance:
        Original section: 4d5223746548b9035a633dd9b8a3bf98ef4371bc27f39756aa409bccde026
        Altered section: 4d5223746548b9035a633dda3bc52a68ef4371bc27f39756aa409bccde026
    Sign a message using the altered private key.
    Attempt to verify the signature using the original public key.
    
To achieve the above steps, I used this script https://gist.github.com/ChristianOConnor/b9a6e1771420df87f2f9f9a2b76df4ac to generate keys. After altering the private key, I tried to use https://github.com/cloudflare/circl/blob/main/sign/dilithium/example_test.go but replaced:  

    // Load it again
    sk2 := mode.PrivateKeyFromBytes(packedSk)
    pk2 := mode.PublicKeyFromBytes(packedPk)

with:  

    privBytes, err := hex.DecodeString(string("PASTE PRIV KEY HERE"))
    sk2 := mode.PrivateKeyFromBytes(privKeyBytes)
    pubBytes, err := hex.DecodeString(string("PASTE PRIV KEY HERE"))
    pk2 := mode.PublicKeyFromBytes(pubKeyBytes)

Also remember to change "Dilithium3" to "Dilithium5"

Expected behavior:

The signature verification should fail when using a modified private key.

Actual behavior:

The signature verification succeeds.

Additional information:

    I've confirmed the keys are generated properly.
    This behavior seems wrong since I'd expect that even a slight modification to the private key would invalidate the signature verification.

**Comment by bwesterb** [comment]
A Dilitihium private key consists of many different values. Changing most of them will cause signatures not to verify anymore. However, modifying `K` will not affect verification. `K` is used to seed the deterministic creation of signatures. You'll notice that if you modify `K`, you will not get the same signature for the same message anymore as you had before modifying `K`.
<img width="610" alt="Screenshot 2023-10-24 at 11 40 33" src="https://github.com/cloudflare/circl/assets/9975/84d9e802-09c3-436e-a888-cef41a94a628">

**Comment by ChristianOConnor** [comment]
Oh that's fascinating and complex lol. But just to confirm... What I've observed is not unexpected behavior? Changing the private key will change the signature, but as long as the private key isn't changed in a significant way, a verification can still be produced?

**Comment by bwesterb** [comment]
It really depends on which part of the private you change.

**Comment by ChristianOConnor** [comment]
Oh gotcha, thanks for clarifying!
