### ISSUE TITLE
does KyberSlash affect this verison of Kyber?

### ISSUE THREAD

**Issue by david415** [cloudflare/circl#472]
i know your Kyber is NIST round 3 but is it vulnerable to kyberslash1 and kyberslash2?

http://kyberslash.cr.yp.to/
http://kyberslash.cr.yp.to/faq.html
http://kyberslash.cr.yp.to/libraries.html

https://www.bleepingcomputer.com/news/security/kyberslash-attacks-put-quantum-encryption-projects-at-risk/

**Comment by bwesterb** [comment]
Circl ≤1.3.6 was vulnerable to Kyberslash2, but not to Kyberslash1. It's [patched](https://github.com/cloudflare/circl/commit/75ef91e8a2f438e6ce2b6e620d236add8be1887d) in 1.3.7. We'll have a security advisory out soon. It's good to note that Kyberslash does not impact ephemeral use, such as in TLS.

**Comment by david415** [comment]
@bwesterb thank you for the timely reply!

**Comment by bwesterb** [comment]
The [advisory](https://github.com/cloudflare/circl/security/advisories/GHSA-9763-4f94-gfch) is out.
