### ISSUE TITLE
ML-DSA?

### ISSUE THREAD

**Issue by OR13** [cloudflare/circl#473]
Per https://csrc.nist.gov/pubs/fips/204/ipd

> ML-DSA is derived from Version 3.1 of CRYSTALS-DILITHIUM [5]. 

I am looking for `ML-DSA-44`, `ML-DSA-65`, `ML-DSA-87`

I checked the modes in https://github.com/cloudflare/circl/blob/ede59c5caa02fc7ef18e27a76cf64f9d88de71a9/sign/dilithium/gen.go#L56

It does not appear there is a direct mapping, is ML-DSA support planned?

**Comment by armfazh** [comment]
Our plan is to produce named packages specific to the final version. Currently, it's work in progress.

**Comment by UladzimirTrehubenka** [comment]
The first standards were recently [finalized](https://www.nist.gov/news-events/news/2024/08/nist-releases-first-3-finalized-post-quantum-encryption-standards)

**Comment by armfazh** [comment]
Closed by #480

**Comment by bwesterb** [comment]
@armfazh We might want to cut a release.
