### ISSUE TITLE
cp-abe: plaintext exceeding a certain length will fail during decryption

### ISSUE THREAD

**Issue by hafeidejiangyou** [cloudflare/circl#484]
Run example_test.go, and change the plaintext like:

`msgStr := `must have the precious 🎃` + strings.Repeat("abc", 1024*10*3)`

It will Encrypt error with "decryption using right attrs should have succeeded"

Is there a limitation on the length of the plaintext?

**Comment by armfazh** [comment]
I've identified the issue, and am preparing documentation for it. 
In short, message is length-prefixed stored with `uint16` prefixes.

**Comment by hafeidejiangyou** [comment]
> I've identified the issue, and am preparing documentation for it. In short, message is length-prefixed stored with `uint16` prefixes.

Are there any other considerations when using uint16? Will larger data types be used in the future?
