### ISSUE TITLE
Align on `purego` build tag.

### ISSUE THREAD

**Issue by mattyclarkson** [cloudflare/circl#491]
golang/go#23172 proposes the de-facto `purego` build tag.

`circl` uses both `purego` _and_ `noasm` build tags, inconsistently.

If a user wants a `purego` build, the build should not include assembly.

Would `circl` be willing to align on `purego` meaning `noasm`?

For example, this is what the upstream golang `crypto` package does: https://go-review.googlesource.com/c/go/+/561935

Another option is to make `purego` and `noasm` equivalent in the code-base if `noasm` needs to be a backwards supported build flag.

I would be willing to contribute the patch.

**Comment by armfazh** [comment]
@mattyclarkson thanks for raising this issue, happy to review your patch.
