### ISSUE TITLE
Unpacking Kyber keys from a FIPS 203 x509 key spec

### ISSUE THREAD

**Issue by jmcrawford45** [cloudflare/circl#496]
Hi all,

I'm encountering an issue where I'm able to correctly encapsulate / decapsulate with a randomly generated key, but I fail to decapsulate when unpacking from a FIPS 203 x509 key spec produced by [BouncyCastle](https://downloads.bouncycastle.org/java/docs/bcprov-jdk18on-javadoc/org/bouncycastle/pqc/crypto/crystals/kyber/KyberKeyParameters.html). I'm loading the public key from t + rho, and I'm loading the private key from s + t + rho + hpk + z. Does this sound like a reasonable mapping / are there some expected transformations required to agree on the same key?

Best,
Jared

**Comment by jmcrawford45** [comment]
Yes, this is using https://github.com/cloudflare/circl/pull/470

**Comment by bwesterb** [comment]
Which version of bouncy castle? They did some [weird things](https://github.com/bcgit/bc-java/commit/249f9328975874a6a22532367b27316dd9d22247#diff-61804c1d5c7e9c246989280f8d2dd774da082b10c5c466c43daccb3930d9ba53) with the private key, and your version might still be on round 3 instead of the IPD.

**Comment by bwesterb** [comment]
Ok, what is this "x509 key spec" about?

**Comment by jmcrawford45** [comment]
The x509 aspect isn't relevant. Basically I'm passing the output of encoded from the key parameters into the relevant unpack functions. E.g. for a public key this is 
```
static byte[] getEncoded(byte[] t, byte[] rho)
    {
        return Arrays.concatenate(t, rho);
    }
```
and for a private key this is
```
public byte[] getEncoded()
    {
        return Arrays.concatenate(new byte[][]{ s, t, rho, hpk, nonce });
    }
```

**Comment by bwesterb** [comment]
With any sane implementation of Kyber, the user should never have to handle the constituents of the keys themselves. What is that about?

**Comment by jmcrawford45** [comment]
I'm have two use cases for loading an existing key generated by BouncyCastle. One is for known answer tests to verify compatibility, and the other is the more standard use case of key encapsulation which requires loading the public key. I'm not directly accessing the constituents, I'm using the getEncoded method and the unpack methods which from reading the code seem to agree on the arrangement and format of consituents. Is there another preferred way to load an existing mlkem key pair in circl?

**Comment by jmcrawford45** [comment]
This was an issue with BouncyCastle version conflicts. Thanks again for taking a look!
