### ISSUE TITLE
Deserialization test failing for BLS12-381

### ISSUE THREAD

**Issue by matteosz** [cloudflare/circl#499]
Hello,

I was working on [Kyber](https://github.com/dedis/kyber) library, a crypto library in Go, and we were using your implementation of BLS12-381. 
We also leverage another implementation of BLS12-381 from [Kilic](https://github.com/kilic/bls12-381).

We were then adding some deserialization tests (from this [commit](https://github.com/AnomalRoil/bls12-381/commit/227d999812d13f92cf80c054a14f31ec5ab6b035)) and noticed that one in particular fails on the Circl implementation, while it succeeds on the Kilic one. Here's the deserialization test:

`Filename: deserialization_fails_with_b_flag_and_a_flag_true.yaml`
```yaml
input: {signature: e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}
output: null
```

Here's the [test code](https://github.com/dedis/kyber/blob/bls12381/pairing/bls12381/bls12381_test.go) for reproducibility (`TestZKCryptoVectorsG1Compressed` and `TestZKCryptoVectorsG2Compressed` tests).

**Comment by armfazh** [comment]
Thanks @matteosz for reporting.
