### ISSUE TITLE
ML-DSA new NIST KAT

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [cloudflare/circl#506]
Observed that [**bas/ml-dsa**](https://github.com/cloudflare/circl/tree/bas/ml-dsa) branch has implementation which OK against [NIST KAT from Apr 15, 2024](https://github.com/usnistgov/ACVP-Server/blob/eb31c8ef41d1f62177960180c16d6ae8b9fba648/gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json).
However there is fresh [NIST KAT from May 23, 2024](https://github.com/usnistgov/ACVP-Server/blob/8b2204159c1b31a3202ff415cc7a9e1058c35fc5/gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json) ([KAT history](https://github.com/usnistgov/ACVP-Server/commits/master/gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json)). So need to fix ML-DSA implementation.

**Comment by bwesterb** [comment]
What's the difference? I intend to match the [standard branch](https://github.com/pq-crystals/dilithium/tree/standard) of the crystal's team until NIST releases the final version of FIPS 204.

**Comment by UladzimirTrehubenka** [comment]
> What's the difference?

**Comment by bwesterb** [comment]
Right, the new test vectors [include changes](https://github.com/open-quantum-safe/liboqs/issues/1850#issuecomment-2242856637) that are expected to be included in the final standard, but aren't published in the ipd (initial public draft) yet. We'll wait for the final draft to be out.

**Comment by UladzimirTrehubenka** [comment]
Fix: sign/mldsa/mldsa{ver}/internal/dilithium.go
replace
PolyDeriveUniformBall(&ch, sig.c[:32]) // SeedSize
with
PolyDeriveUniformBall(&ch, sig.c[:64]) // CTildeSize

**Comment by bwesterb** [comment]
I updated the ML-DSA PR to FIPS 204. There are no test vectors yet, so we'll wait merging until we have crosschecked this implementation with another.
