### ISSUE TITLE
ACVP test "sigVer" is not used in #480 

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [cloudflare/circl#516]
Observed after merge #480:
https://github.com/cloudflare/circl/blob/main/sign/mldsa/mldsa87/acvp_test.go#L48
has "keyGen" and "sigGen" but not "sigVer" (implemented already). However "sigVer" after enable won't work because need to implement a function similar to unsafeSignInternal() like unsafeVerifyInternal(), because exported Verify() uses ctx (empty), but two bytes with zero values are added before verified message anyway.

**Comment by bwesterb** [comment]
Whoops! Thanks for reporting. @armfazh solved it.
