### ISSUE TITLE
mldsa87 : After generate the public key and private key getting error during sign the message

### ISSUE THREAD

**Issue by ravinderncog** [cloudflare/circl#523]
I am using  github.com/cloudflare/circl/sign/mldsa/mldsa87 to generate the public key and private key, after this sign a message but at this stage getting error. I  would highly appreciate your support to resolve the below error. 

Logs:
Loading keys from files...
Keys loaded successfully.

Signing message: This is a test message for ML-DSA87.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4e82d8]

goroutine 1 [running]:
github.com/cloudflare/circl/sign/mldsa/mldsa87.(*PrivateKey).Sign(0xc0000bc000, {0xc000113e20?, 0x4a6430?}, {0xc00001c570, 0x24, 0x24}, {0x0, 0x0})
        /home/user/go/pkg/mod/github.com/cloudflare/circl@v1.5.0/sign/mldsa/mldsa87/dilithium.go:212 +0x58
main.SignMessage({0xc00001c570?, 0xc00005e028?, 0x519550?}, 0x15?)
        /home/user/Desktop/ncog-post-quantm/kyber/main.go:52 +0x45
main.main()
        /home/user/Desktop/ncog-post-quantm/kyber/main.go:93 +0x2ff
exit status 2

Codebase: 

package main

import (
	"crypto/rand"
	"encoding/gob"
	"fmt"
	"log"
	"os"

	"github.com/cloudflare/circl/sign/mldsa/mldsa87"
)

// saveToFile serializes and saves data to a file using gob.
func saveToFile(filePath string, data interface{}) {
	file, err := os.Create(filePath)
	if err != nil {
		log.Fatalf("Failed to create file %s: %v", filePath, err)
	}
	defer file.Close()

	encoder := gob.NewEncoder(file)
	if err := encoder.Encode(data); err != nil {
		log.Fatalf("Failed to encode data to file %s: %v", filePath, err)
	}
}

// loadFromFile deserializes data from a file using gob.
func loadFromFile(filePath string, data interface{}) {
	file, err := os.Open(filePath)
	if err != nil {
		log.Fatalf("Failed to open file %s: %v", filePath, err)
	}
	defer file.Close()

	decoder := gob.NewDecoder(file)
	if err := decoder.Decode(data); err != nil {
		log.Fatalf("Failed to decode data from file %s: %v", filePath, err)
	}
}

// GenerateKeyPair generates an ML-DSA87 key pair.
func GenerateKeyPair() (*mldsa87.PublicKey, *mldsa87.PrivateKey) {
	publicKey, privateKey, err := mldsa87.GenerateKey(rand.Reader)
	if err != nil {
		log.Fatalf("Failed to generate ML-DSA87 key pair: %v", err)
	}
	return publicKey, privateKey
}

// SignMessage signs a message using the private key.
func SignMessage(message []byte, privateKey *mldsa87.PrivateKey) []byte {
	signature, err := privateKey.Sign(rand.Reader, message, nil)
	if err != nil {
		log.Fatalf("Failed to sign message: %v", err)
	}
	return signature
}

// VerifySignature verifies the message's signature using the public key.
func VerifySignature(message, signature []byte, publicKey *mldsa87.PublicKey) bool {
	return mldsa87.Verify(publicKey, message, nil, signature)
}

func main() {
	// File paths for storing the keys
	pubFile := "mldsa87_public.gob"
	privFile := "mldsa87_private.gob"

	var publicKey *mldsa87.PublicKey
	var privateKey *mldsa87.PrivateKey

	// Step 1: Check if keys already exist
	if _, err := os.Stat(pubFile); os.IsNotExist(err) {
		// Generate new keys and save them
		fmt.Println("Generating ML-DSA87 key pair...")
		publicKey, privateKey = GenerateKeyPair()
		saveToFile(pubFile, publicKey)
		saveToFile(privFile, privateKey)
		fmt.Println("Keys generated and saved successfully.")
	} else {
		// Load keys from files
		fmt.Println("Loading keys from files...")
		publicKey = new(mldsa87.PublicKey)
		privateKey = new(mldsa87.PrivateKey)
		loadFromFile(pubFile, publicKey)
		loadFromFile(privFile, privateKey)
		fmt.Println("Keys loaded successfully.")
	}

	// Step 2: Sign a message
	message := []byte("This is a test message for ML-DSA87.")
	fmt.Printf("\nSigning message: %s\n", message)
	signature := SignMessage(message, privateKey)
	fmt.Printf("Signature: %x\n", signature)

	// Step 3: Verify the signature
	fmt.Println("\nVerifying the signature...")
	if VerifySignature(message, signature, publicKey) {
		fmt.Println("Signature verification successful!")
	} else {
		fmt.Println("Signature verification failed! ")
	}
}

**Comment by bwesterb** [comment]
You have to pass `crypto.Hash(0)` as SignerOpts.
