### ISSUE TITLE
Encrypted SharedSecret location (Sike)?

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [cloudflare/circl#80]
Where is the encrypted sharedSecret stored when you call:
`kem.Encapsulate(ciphertext, sharedSecret, pubB)`
 
My thought was kem.msg that struct property is unexported and not accessible.

**Comment by henrydcase** [comment]
it's not stored anywhere. The ``kem.Encapsulate`` performs encapsulation and returns ``ciphertext`` and ``sharedSecret`` 

Maybe this test will help to understand how encapsulate/decapsulate interact.
https://github.com/cloudflare/circl/blob/master/dh/sidh/sike_test.go#L170
