### ISSUE TITLE
Shake is crashing when using unsafe pointer casting

### ISSUE THREAD

**Issue by armfazh** [cloudflare/circl#89]
In CI, there is triggered an crash error inside shake package.
Details: 
 - https://app.circleci.com/jobs/github/cloudflare/circl/1647
 - https://app.circleci.com/jobs/github/cloudflare/circl/1648

Bas, could you please take a look on this.

**Comment by armfazh** [comment]
https://golang.org/doc/go1.14#compiler
> This release (1.14) adds -d=checkptr as a compile-time option for adding instrumentation to check that Go code is following unsafe.Pointer safety rules dynamically.

It seems that the unsafe conversion is failing happening only on Go 1.14.

**Comment by bwesterb** [comment]
This is the same issue as reported for Go in https://github.com/golang/go/issues/35173 which was fixed by https://go-review.googlesource.com/c/crypto/+/203837/

**Comment by bwesterb** [comment]
Ok, so this problem also occurs upstream: https://github.com/golang/go/issues/37644
